{{- if .Values.networkPolicy.enabled -}}
{{- if not .Values.networkPolicy.ingressFrom -}}
{{- fail "networkPolicy.ingressFrom is required when networkPolicy.enabled is true" -}}
{{- end -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "ok-fine.fullname" . }}
  labels:
    {{- include "ok-fine.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "ok-fine.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        {{- toYaml .Values.networkPolicy.ingressFrom | nindent 8 }}
      ports:
        - protocol: TCP
          port: 8080
{{- end }}
